# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d447ff31acb5e23fd1516b1ff692aa1bd879ad0ff501d7a68447fe5eefc88716e274e72f499fd215e185ce1566fc9f23c3535420c109934bb7ee10fb31df338

test:
  secret_key_base: edade599e9012d6524dd1f613ef3555300d5901c0688848c68cc5d30821b604df26265707b008cad264e8b05ba641a9cd512c72eb13cc59e94588b1980e1cd77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
